<?php

return [
    'employer' => [
        'Admin & Clerical',
        'Advanced Nurse Practitioner',
        'Cleaner',
        'Clinical Pharmacist',
        'Community Nurse',
        'Community Psychiatric Nurse',
        'Counsellor',
        'District Nurse',
        'Driver',
        'Drug and Alcohol worker',
        'GP',
        'Health Care Assistant',
        'Mental Health Nurse',
        'Physicians Associate/Assistant',
        'Phlebotomist',
        'Practice Manager',
        'Practice Nurse',
        'Read Coder',
        'Receptionist',
        'Social Worker',
        'Secretary',
    ],
    'freelancer' => [
        'Advanced Nurse Practitioner',
        'Clinical Pharmacist',
        'Community Nurse',
        'Community Psychiatric Nurse',
        'Counsellor',
        'District Nurse',
        'GP',
        'Mental Health Nurse',
        'Physicians Associate/Assistant',
        'Practice Nurse',
        'Social Worker',
    ],
    'support' => [
        'Admin & Clerical',
        'Cleaner',
        'Driver',
        'Drug and Alcohol worker',
        'Health Care Assistant',
        'Phlebotomist',
        'Practice Manager',
        'Read Coder',
        'Receptionist',
        'Secretary',
    ],
];