<?php

return [
    'employer' => [
        'Admin & Clerical',
        'Advanced Nurse Practitioner',
        'Carer',
        'Cleaner',
        'Clinical Pharmacist',
        'Community Nurse',
        'Community Psychiatric Nurse',
        'Counsellor',
        'District Nurse',
        'Dietician',
        'Driver',
        'Drug and Alcohol worker',
        'GP',
        'Health Care Assistant',
        'Health Care Assistant(Student Nurse)',
        'Health Care Assistant(Medical Student)',
        'Mental Health Nurse',
        'Nursing Associate',
        'Optometrist',
        'Paramedic',
        'Pharmacist',
        'Physicians Associate/Assistant',
        'Phlebotomist',
        'Practice Manager',
        'Practice Nurse',
        'Read Coder',
        'Receptionist',
        'Social Worker',
        'Secretary',
    ],
    'freelancer' => [
        'Advanced Nurse Practitioner',
        'Clinical Pharmacist',
        'Community Nurse',
        'Community Psychiatric Nurse',
        'Dietician',
        'District Nurse',
        'GP',
        'Mental Health Nurse',
        'Nursing Associate',
        'Optometrist',
        'Paramedic',
        'Pharmacist',
        'Practice Nurse',
        'Social Worker',
    ],
    'support' => [
        'Admin & Clerical',
        'Carer',
        'Cleaner',
        'Counsellor',
        'Driver',
        'Drug and Alcohol worker',
        'Health Care Assistant',
        'Health Care Assistant(Student Nurse)',
        'Health Care Assistant(Medical Student)',
        'Phlebotomist',
        'Physicians Associate/Assistant',
        'Practice Manager',
        'Read Coder',
        'Receptionist',
        'Secretary',
    ],
];